// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore.Model;

namespace NetCore.BasicsFrame.Migrations
{
    [DbContext(typeof(NetCoreBaseDBContext))]
    partial class NetCoreBaseDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCore.Model.Models.SYSUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addrees")
                        .HasColumnType("NvarChar(100)");

                    b.Property<int?>("Age")
                        .HasColumnType("Int");

                    b.Property<DateTime?>("CreatTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatUser")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("NvarChar(36)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("LoginName")
                        .HasColumnType("NvarChar(18)");

                    b.Property<string>("LoginPwd")
                        .HasColumnType("NvarChar(18)");

                    b.Property<string>("Name")
                        .HasColumnType("NvarChar(20)");

                    b.Property<string>("Phone")
                        .HasColumnType("NvarChar(15)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("DateTime");

                    b.Property<Guid?>("UpdateUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID");

                    b.ToTable("SYSUser");
                });
#pragma warning restore 612, 618
        }
    }
}
